# Generated by Django 4.1 on 2022-09-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('c_code', models.CharField(max_length=10)),
                ('l_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=20)),
                ('dist', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=255)),
            ],
        ),
    ]
