# Generated by Django 4.1 on 2022-09-02 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_langs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Langs',
            new_name='Lang',
        ),
    ]
